<?php

declare(strict_types=1);

/**
 * Headless Matomo bootstrap — the tracking-stack counterpart to the PrestaShop
 * provisioning sidecar. Runs once from the matomo image against matomodb and, via
 * Matomo's own classes, does what the web install wizard would: write
 * config.ini.php, create the schema, install the plugins, create the super user,
 * and create the TimberWorks site as an Ecommerce site (→ idSite 1). Idempotent.
 *
 * Note: a CLI bootstrap loads NO plugins by default (the console does it via the
 * FrontController). We must call Manager::loadActivatedPlugins() right after
 * Environment init — otherwise plugin tables are missing from createTables() and
 * measurable types like 'website' aren't registered, so addSite() fails.
 *
 * Config comes from the environment (see config/matomo/default.env). Values are
 * version-coupled to Matomo's internal API on purpose — pinned to matomo:5-apache.
 */

use Piwik\Access;
use Piwik\Common;
use Piwik\Db;
use Piwik\DbHelper;
use Piwik\Application\Environment;
use Piwik\Plugin\Manager as PluginManager;
use Piwik\Plugins\SitesManager\API as SitesManagerApi;
use Piwik\Plugins\UsersManager\API as UsersManagerApi;

const ROOT = '/var/www/html';
const PREFIX = 'matomo_';

function say(string $msg): void
{
    fwrite(STDOUT, '[matomo-sidecar] ' . $msg . PHP_EOL);
}

function env(string $key, string $default = ''): string
{
    $value = getenv($key);

    return $value === false || $value === '' ? $default : $value;
}

$dbHost = env('MATOMO_DATABASE_HOST', 'matomodb');
$dbName = env('MATOMO_DATABASE_DBNAME', env('MYSQL_DATABASE', 'matomo'));
$dbUser = env('MATOMO_DATABASE_USERNAME', env('MYSQL_USER', 'matomo'));
$dbPass = env('MATOMO_DATABASE_PASSWORD', env('MYSQL_PASSWORD', 'matomo'));

$adminLogin = env('MATOMO_ADMIN_LOGIN', 'admin');
$adminPass = env('MATOMO_ADMIN_PASSWORD', 'changeme_demo');
$adminEmail = env('MATOMO_ADMIN_EMAIL', 'admin@timberworks.test');
$siteName = env('MATOMO_SITE_NAME', 'TimberWorks');
$siteUrl = env('MATOMO_SITE_URL', 'https://localhost/');

// 1. Wait for the database to accept connections (no healthcheck on matomodb).
$deadline = time() + 120;
while (true) {
    $link = @mysqli_connect($dbHost, $dbUser, $dbPass, $dbName);
    if ($link instanceof mysqli) {
        mysqli_close($link);
        break;
    }
    if (time() > $deadline) {
        fwrite(STDERR, "[matomo-sidecar] database {$dbHost} not reachable after 120s\n");
        exit(1);
    }
    say("waiting for database {$dbHost}...");
    sleep(3);
}

// 2. Seed config.ini.php so Matomo boots against our database.
$configFile = ROOT . '/config/config.ini.php';
if (!is_file($configFile)) {
    $salt = bin2hex(random_bytes(16));
    $ini = "; <?php exit; ?> DO NOT REMOVE THIS LINE\n"
        . "; generated by the matomo provisioning sidecar\n\n"
        . "[database]\n"
        . "host = \"{$dbHost}\"\n"
        . "username = \"{$dbUser}\"\n"
        . "password = \"{$dbPass}\"\n"
        . "dbname = \"{$dbName}\"\n"
        . "tables_prefix = \"" . PREFIX . "\"\n"
        . "charset = \"utf8mb4\"\n\n"
        . "[General]\n"
        . "salt = \"{$salt}\"\n"
        . "trusted_hosts[] = \"localhost\"\n"
        . "trusted_hosts[] = \"localhost:8080\"\n"
        . "trusted_hosts[] = \"gateway\"\n"
        . "trusted_hosts[] = \"matomo\"\n";
    if (!is_dir(dirname($configFile))) {
        mkdir(dirname($configFile), 0o755, true);
    }
    file_put_contents($configFile, $ini);
    say('wrote config.ini.php');
} else {
    say('config.ini.php already present');
}

// 3. Boot the Matomo kernel (mirrors the console bootstrap) and LOAD the plugins.
define('PIWIK_DOCUMENT_ROOT', ROOT);
define('PIWIK_INCLUDE_PATH', ROOT);
require ROOT . '/core/bootstrap.php';

$environment = new Environment('cli');
$environment->init();
PluginManager::getInstance()->loadActivatedPlugins(); // must precede createTables/addSite

// 4. Create the schema on a fresh database (now includes plugin tables).
$installed = false;
try {
    $installed = DbHelper::getInstallVersion() !== '';
} catch (\Throwable $e) {
    $installed = false; // the option table doesn't exist yet
}

if (!$installed) {
    say('creating Matomo tables...');
    DbHelper::createTables();
    DbHelper::createAnonymousUser();
    DbHelper::recordInstallVersion();
    say('schema created');
} else {
    say('schema already present (install version ' . DbHelper::getInstallVersion() . ')');
}

// 5. Install plugins, create the super user + the Ecommerce site (as superuser).
try {
    Access::doAsSuperUser(function () use (
        $adminLogin, $adminPass, $adminEmail, $siteName, $siteUrl
    ) {
        PluginManager::getInstance()->installLoadedPlugins(); // idempotent

        $users = UsersManagerApi::getInstance();
        $userExists = (bool) Db::fetchOne(
            'SELECT COUNT(*) FROM ' . Common::prefixTable('user') . ' WHERE login = ?',
            [$adminLogin]
        );
        if (!$userExists) {
            $users->addUser($adminLogin, $adminPass, $adminEmail);
            $users->setSuperUserAccess($adminLogin, true);
            say("created super user '{$adminLogin}'");
        } else {
            say("super user '{$adminLogin}' already exists");
        }

        $siteCount = (int) Db::fetchOne('SELECT COUNT(*) FROM ' . Common::prefixTable('site'));
        if ($siteCount === 0) {
            $idSite = SitesManagerApi::getInstance()->addSite($siteName, [$siteUrl], 1); // 3rd arg = ecommerce
            say("created Ecommerce site '{$siteName}' -> idSite {$idSite}");
        } else {
            say("site(s) already present ({$siteCount}) — leaving as is");
        }
    });
} catch (\Throwable $e) {
    fwrite(STDERR, '[matomo-sidecar] ERROR during setup: ' . $e->getMessage() . "\n");
    fwrite(STDERR, $e->getTraceAsString() . "\n");
    exit(1);
}

// Apply component/dimension DB updates via Matomo's own updater — createTables()
// leaves the log-table dimension columns out, so without this the app shows
// "database upgrade required". Delegated to the console updater; idempotent.
say('running database updater...');
$updateExit = 0;
passthru(PHP_BINARY . ' ' . escapeshellarg(ROOT . '/console') . ' core:update --yes --no-interaction 2>&1', $updateExit);
if ($updateExit !== 0) {
    fwrite(STDERR, "[matomo-sidecar] core:update failed (exit {$updateExit})\n");
    exit($updateExit);
}

say('done.');
